
set(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "bitconnect desktop")
SET(CPACK_PACKAGE_VENDOR "coinyee")

#SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
#SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")

SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "0")

if(WIN32)
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "bitconnect")
else()
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "/")
endif()

SET(CPACK_PACKAGE_EXECUTABLES "chainspaywallet" "chainspaywallet")

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "microcai") #required

SET(CPACK_SOURCE_IGNORE_FILES "${CPACK_SOURCE_IGNORE_FILES};${CMAKE_CURRENT_BINARY_DIR};\\\\.git;\\\\.kdev.*;\\\\.travis\\\\.yml")

set(CPACK_PACKAGE_NAME chainspaywallet)

set(CPACK_DMG_FORMAT "udzo")